In [1]:
#-----------------------------------Patient Registries-----------------------------------#
#importing all the essential library # from this line!
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns
from sklearn.feature_selection import chi2
from sklearn.model_selection import train_test_split
#Patient Registries##
registries = pd.read_csv('PatientRegistry_cleaned_final.csv', sep=',', error_bad_lines=False, index_col=False, dtype='unicode')
registries.head()

,Unnamed: 0,nct_id,study_type,phase,start_month_year,primary_completion_month_year,has_dmc,overall_status,brief_title,why_stopped,...,lead_Sponsor,Agency_Class_Lead,lead_or_collaborator,subjects_affected_Binary,subjects_at_risk_binary,responsible_party_type,enrollment_bins,minimum_age_bins,maximum_age_bins,stopped
0,37,NCT02618707,Observational [Patient Registry],Not_Interventional,15-Dec,16-Mar,TRUE,Completed,Lactate Levels During Cardiopulmonary Bypass i...,not stopped/ not stated,...,Assiut University,Other,lead,FALSE,FALSE,Principal Investigator,VLOW,Children,Children,not stopped/ not stated
1,60,NCT03938909,Observational [Patient Registry],Not_Interventional,1-Mar-19,1-Sep-19,FALSE,Recruiting,Ccf mtDNA as a Neurodegenerative Biomarker,not stopped/ not stated,...,Neuromed IRCCS,Other,lead,FALSE,FALSE,Principal Investigator,MED,Youth,Seniors,not stopped/ not stated
2,94,NCT04398186,Observational [Patient Registry],Not_Interventional,1-Jun-20,30-Oct-20,FALSE,Completed,The Effect of Polycystic Ovary Syndrome on Pel...,not stopped/ not stated,...,Giresun University,Other,lead,FALSE,FALSE,Principal Investigator,VLOW,Youth,Adults,not stopped/ not stated
3,222,NCT01102556,Observational [Patient Registry],Not_Interventional,4-Jul,30-Dec,TRUE,Recruiting,PANCREATIC DISEASE COHORT A Registry and Biosp...,not stopped/ not stated,...,Columbia University,Other,lead,FALSE,FALSE,Principal Investigator,MED,Youth,Seniors,not stopped/ not stated
4,244,NCT03517670,Observational [Patient Registry],Not_Interventional,10-Jun-18,30-May-21,FALSE,Recruiting,Safety of Intravenous Milrinone for the Treatm...,not stopped/ not stated,...,Nantes University Hospital,Other,lead,FALSE,FALSE,Sponsor,VLOW,Youth,no_criteria,not stopped/ not stated

In [2]:
del registries['nct_id']
registries.dtypes

Unnamed: 0                       object
study_type                       object
phase                            object
start_month_year                 object
primary_completion_month_year    object
has_dmc                          object
overall_status                   object
brief_title                      object
why_stopped                      object
enrollment_type                  object
study_first_submitted_date       object
number_of_facilities_bins        object
number_of_arms                   object
number_of_groups_bins            object
country_name                     object
condition_name                   object
actual_duration_bins             object
were_results_reported            object
has_single_facility              object
allocation                       object
masking                          object
intervention_model               object
primary_purpose                  object
observational_model              object
gender                           object
healthy_volunteers               object
sampling_method                  object
gender_based                     object
intervention_type                object
lead_Sponsor                     object
Agency_Class_Lead                object
lead_or_collaborator             object
subjects_affected_Binary         object
subjects_at_risk_binary          object
responsible_party_type           object
enrollment_bins                  object
minimum_age_bins                 object
maximum_age_bins                 object
stopped                          object
dtype: object

In [3]:
registries.describe(include='all')

,Unnamed: 0,study_type,phase,start_month_year,primary_completion_month_year,has_dmc,overall_status,brief_title,why_stopped,enrollment_type,...,lead_Sponsor,Agency_Class_Lead,lead_or_collaborator,subjects_affected_Binary,subjects_at_risk_binary,responsible_party_type,enrollment_bins,minimum_age_bins,maximum_age_bins,stopped
count,5402,5402,5402,5402,5402,5402,5402,5402,5402,5402,...,5402,5402,5402,5402,5402,5402,5402,5402,5402,5402
unique,5402,1,1,1550,1395,3,9,5400,136,3,...,2443,4,2,2,2,3,6,5,5,2
top,74385,Observational [Patient Registry],Not_Interventional,14-Jan,31-Dec-20,FALSE,Recruiting,Mid-term Data Collection of the Treatment of I...,not stopped/ not stated,Anticipated,...,Assiut University,Other,lead,FALSE,FALSE,Principal Investigator,VLOW,Youth,no_criteria,not stopped/ not stated
freq,1,5402,5402,63,97,3248,1974,2,5258,3423,...,72,4723,3728,5357,5337,2712,3260,3612,3253,5258

In [5]:
#Getting all the categorical columns except the overall status
categorical_columns2 = registries.select_dtypes(exclude = 'number').drop('overall_status', axis = 1).columns
registries.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5402 entries, 0 to 5401
Data columns (total 39 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Unnamed: 0                     5402 non-null   object
 1   study_type                     5402 non-null   object
 2   phase                          5402 non-null   object
 3   start_month_year               5402 non-null   object
 4   primary_completion_month_year  5402 non-null   object
 5   has_dmc                        5402 non-null   object
 6   overall_status                 5402 non-null   object
 7   brief_title                    5402 non-null   object
 8   why_stopped                    5402 non-null   object
 9   enrollment_type                5402 non-null   object
 10  study_first_submitted_date     5402 non-null   object
 11  number_of_facilities_bins      5402 non-null   object
 12  number_of_arms                 5402 non-null   object
 13  number_of_groups_bins          5402 non-null   object
 14  country_name                   5402 non-null   object
 15  condition_name                 5402 non-null   object
 16  actual_duration_bins           5402 non-null   object
 17  were_results_reported          5402 non-null   object
 18  has_single_facility            5402 non-null   object
 19  allocation                     5402 non-null   object
 20  masking                        5402 non-null   object
 21  intervention_model             5402 non-null   object
 22  primary_purpose                5402 non-null   object
 23  observational_model            5402 non-null   object
 24  gender                         5402 non-null   object
 25  healthy_volunteers             5402 non-null   object
 26  sampling_method                5402 non-null   object
 27  gender_based                   5402 non-null   object
 28  intervention_type              5402 non-null   object
 29  lead_Sponsor                   5402 non-null   object
 30  Agency_Class_Lead              5402 non-null   object
 31  lead_or_collaborator           5402 non-null   object
 32  subjects_affected_Binary       5402 non-null   object
 33  subjects_at_risk_binary        5402 non-null   object
 34  responsible_party_type         5402 non-null   object
 35  enrollment_bins                5402 non-null   object
 36  minimum_age_bins               5402 non-null   object
 37  maximum_age_bins               5402 non-null   object
 38  stopped                        5402 non-null   object
dtypes: object(39)
memory usage: 1.6+ MB

In [6]:
pd.crosstab(registries['overall_status'], registries['lead_Sponsor'])

lead_Sponsor,251 Hellenic Air Force & VA General Hospital,"404 General Military Hospital, Larissa",4YouandMe,ABDULZAHRA HUSSAIN,AC Camargo Cancer Center,AHEPA University Hospital,AHMED ABDULQADER HAMMOUDA ABOU SHALL,ANA TORRES-ORTUâˆšÃ«O,"ANRS, Emerging Infectious Diseases",AO Clinical Investigation and Publishing Documentation,...,lvshan,marco matucci cerinic,miR Scientific LLC,noha mohamed elzaydy,nooshin dalili,wenbinlu,xCures,yongjun wang,âˆšÃ…ngel Becerra,âˆšÃ¡AÆ’Ã»LAYAN âˆšÃ¡AKIR
overall_status,,,,,,,,,,,,,,,,,,,,,
"Active, not recruiting",0,0,0,0,0,0,0,0,0,2,...,0,0,0,0,0,0,0,0,0,0
Completed,1,0,0,1,0,0,0,0,0,1,...,1,0,0,0,1,0,0,0,1,1
Enrolling by invitation,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Not yet recruiting,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
Recruiting,0,0,1,0,0,3,0,0,1,7,...,0,0,1,0,0,1,1,0,0,0
Suspended,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Terminated,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Unknown status,0,1,0,0,1,0,1,1,0,0,...,0,1,0,1,0,0,0,1,0,0
Withdrawn,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [7]:
# Import the function
from scipy.stats import chi2_contingency
#Testing the relationship
chi_res = chi2_contingency(pd.crosstab(registries['overall_status'], registries['lead_Sponsor']))
print('Chi2 Statistic: {}, p-value: {}'.format(chi_res[0], chi_res[1]))

Chi2 Statistic: 23471.489729861576, p-value: 1.898099939083441e-78

In [8]:
# Import the function
from scipy.stats import chi2_contingency
chi2_check = []
for i in categorical_columns2:
    if chi2_contingency(pd.crosstab(registries['overall_status'], registries[i]))[1] < 0.05:
        chi2_check.append('Reject Null Hypothesis')
    else:
        chi2_check.append('Fail to Reject Null Hypothesis')
res = pd.DataFrame(data = [categorical_columns2, chi2_check] 
             ).T 
res.columns = ['Column', 'Hypothesis']
print(res)

                           Column                      Hypothesis
0                      Unnamed: 0  Fail to Reject Null Hypothesis
1                      study_type  Fail to Reject Null Hypothesis
2                           phase  Fail to Reject Null Hypothesis
3                start_month_year          Reject Null Hypothesis
4   primary_completion_month_year          Reject Null Hypothesis
5                         has_dmc          Reject Null Hypothesis
6                     brief_title  Fail to Reject Null Hypothesis
7                     why_stopped          Reject Null Hypothesis
8                 enrollment_type          Reject Null Hypothesis
9      study_first_submitted_date          Reject Null Hypothesis
10      number_of_facilities_bins          Reject Null Hypothesis
11                 number_of_arms  Fail to Reject Null Hypothesis
12          number_of_groups_bins          Reject Null Hypothesis
13                   country_name          Reject Null Hypothesis
14                 condition_name  Fail to Reject Null Hypothesis
15           actual_duration_bins          Reject Null Hypothesis
16          were_results_reported          Reject Null Hypothesis
17            has_single_facility          Reject Null Hypothesis
18                     allocation  Fail to Reject Null Hypothesis
19                        masking  Fail to Reject Null Hypothesis
20             intervention_model  Fail to Reject Null Hypothesis
21                primary_purpose  Fail to Reject Null Hypothesis
22            observational_model          Reject Null Hypothesis
23                         gender          Reject Null Hypothesis
24             healthy_volunteers          Reject Null Hypothesis
25                sampling_method          Reject Null Hypothesis
26                   gender_based  Fail to Reject Null Hypothesis
27              intervention_type          Reject Null Hypothesis
28                   lead_Sponsor          Reject Null Hypothesis
29              Agency_Class_Lead          Reject Null Hypothesis
30           lead_or_collaborator          Reject Null Hypothesis
31       subjects_affected_Binary          Reject Null Hypothesis
32        subjects_at_risk_binary          Reject Null Hypothesis
33         responsible_party_type          Reject Null Hypothesis
34                enrollment_bins          Reject Null Hypothesis
35               minimum_age_bins          Reject Null Hypothesis
36               maximum_age_bins          Reject Null Hypothesis
37                        stopped          Reject Null Hypothesis

In [33]:
property_dummies = pd.get_dummies(data = registries[['overall_status', 'primary_purpose']], columns = ['overall_status'])
property_dummies

,primary_purpose,"overall_status_Active, not recruiting",overall_status_Completed,overall_status_Enrolling by invitation,overall_status_Not yet recruiting,overall_status_Recruiting,overall_status_Suspended,overall_status_Terminated,overall_status_Unknown status,overall_status_Withdrawn
0,not_provided,0,1,0,0,0,0,0,0,0
1,not_provided,0,0,0,0,1,0,0,0,0
2,not_provided,0,1,0,0,0,0,0,0,0
3,not_provided,0,0,0,0,1,0,0,0,0
4,not_provided,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
5397,not_provided,0,0,0,0,0,0,0,1,0
5398,not_provided,0,0,0,0,1,0,0,0,0
5399,not_provided,0,0,0,0,0,0,0,0,1
5400,not_provided,0,0,0,0,1,0,0,0,0
5401,not_provided,0,0,0,0,1,0,0,0,0

In [34]:
pd.crosstab(property_dummies['primary_purpose'], property_dummies['overall_status_Completed'])

overall_status_Completed     0     1
primary_purpose
not_provided              3791  1611

In [35]:
check = {}
for i in res[res['Hypothesis'] == 'Reject Null Hypothesis']['Column']:
    dummies = pd.get_dummies(registries[i])
    bon_p_value = 0.05/registries[i].nunique()
    for series in dummies:
        if chi2_contingency(pd.crosstab(registries['overall_status'], dummies[series]))[1] < bon_p_value:
            check['{}-{}'.format(i, series)] = 'Reject Null Hypothesis'
        else:
            check['{}-{}'.format(i, series)] = 'Fail to Reject Null Hypothesis'
res_chi_ph = pd.DataFrame(data = [check.keys(), check.values()]).T
res_chi_ph.columns = ['Pair', 'Hypothesis']
res_chi_ph
#res_chi_ph.to_csv("Capstone.ChiTest_PR.csv")

                                  Pair                      Hypothesis
0            start_month_year-1-Apr-01  Fail to Reject Null Hypothesis
1            start_month_year-1-Apr-07  Fail to Reject Null Hypothesis
2            start_month_year-1-Apr-08  Fail to Reject Null Hypothesis
3            start_month_year-1-Apr-11  Fail to Reject Null Hypothesis
4            start_month_year-1-Apr-12  Fail to Reject Null Hypothesis
...                                ...                             ...
10724             enrollment_bins-VLOW          Reject Null Hypothesis
10725           enrollment_bins-V_HIGH          Reject Null Hypothesis
10726     enrollment_bins-not_provided          Reject Null Hypothesis
10727  stopped-not stopped/ not stated          Reject Null Hypothesis
10728                  stopped-stopped          Reject Null Hypothesis

[10729 rows x 2 columns]